import './style.css';

const app=document.querySelector('#app');
const state={cv:null,stream:null,video:null,game:null,raf:0,score:0,best:Number(localStorage.getItem('camrush-best')||0)};
const games=[
{id:'catch',icon:'✦',title:'Catch Rush',tag:'HAND',desc:'Catch glowing targets with your index finger.',color:'cyan',time:'45 SEC'},
{id:'dodge',icon:'◉',title:'Face Dodge',tag:'FACE',desc:'Lean left and right to dodge falling gates.',color:'violet',time:'ENDLESS'},
{id:'smile',icon:'◒',title:'Smile Blast',tag:'FACE',desc:'Smile to charge your blast and clear targets.',color:'pink',time:'45 SEC'},
{id:'pong',icon:'▰',title:'Hand Pong',tag:'HAND',desc:'Move your hand to control the paddle.',color:'lime',time:'ENDLESS'}];

app.innerHTML='<div class="shell"><header class="topbar"><a class="brand" href="./"><span class="brand-mark">◈</span><span>CAM<span>RUSH</span></span></a><div class="top-actions"><span class="pill"><i></i> CAMERA LOCAL</span><button class="icon-btn" id="installBtn" hidden>Install</button></div></header><main><section class="hero"><div class="eyebrow">CAMERA ARCADE <b>•</b> ZERO SIGN-UP</div><h1>Move. Play.<br><em>Rush.</em></h1><p>Four quick camera games. Your movements are the controller.</p><div class="hero-actions"><button class="primary" id="playBtn">PLAY NOW <span>→</span></button><span class="hint">Chrome / Edge / Safari</span></div></section><section class="games-head"><div><span class="section-kicker">THE ARCADE</span><h2>Pick your rush.</h2></div><div class="score-chip">BEST <strong id="bestScore">'+state.best+'</strong></div></section><section class="grid" id="gameGrid"></section><section class="trust"><div><span class="trust-icon">⌁</span><div><b>Processed on your device</b><small>Your camera feed is used locally by the game.</small></div></div><div><span class="trust-icon">⚡</span><div><b>Fast by design</b><small>Vision models load only when a game starts.</small></div></div><div><span class="trust-icon">＋</span><div><b>Installable</b><small>Add CamRush to your home screen.</small></div></div></section></main><footer><span>CAMRUSH</span><span>Four games. One camera.</span></footer></div><div class="modal hidden" id="gameModal"><div class="game-window"><div class="gamebar"><div><span id="gameTag"></span><b id="gameTitle"></b></div><div class="gamebar-right"><span id="gameScore">0</span><button id="closeGame">×</button></div></div><div class="stage-wrap"><canvas id="gameCanvas"></canvas><video id="camera" playsinline muted></video><div class="loading" id="loading"><div class="spinner"></div><b>Waking the camera…</b><small>Allow camera access to play.</small></div><div class="countdown hidden" id="countdown"></div><div class="game-tip" id="gameTip"></div></div><div class="game-footer"><span id="gameStatus">GET READY</span><button class="secondary" id="restartGame">RESTART</button></div></div></div><div class="toast hidden" id="toast"></div>';

const grid=document.querySelector('#gameGrid');
grid.innerHTML=games.map(g=>'<article class="card '+g.color+'" data-game="'+g.id+'"><div class="card-art"><div class="orb">'+g.icon+'</div><span class="game-time">'+g.time+'</span><span class="card-tag">'+g.tag+'</span></div><div class="card-copy"><h3>'+g.title+'</h3><p>'+g.desc+'</p><button class="play-card">PLAY <span>→</span></button></div></article>').join('');

let deferredInstall=null;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;document.querySelector('#installBtn').hidden=false});
document.querySelector('#installBtn').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null}};
function toast(m){const t=document.querySelector('#toast');t.textContent=m;t.classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.add('hidden'),3000)}
async function loadVision(){if(state.cv)return state.cv;state.cv=await import('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22/+esm');return state.cv}
async function startCamera(){if(state.stream)stopCamera();state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:960},height:{ideal:540}},audio:false});state.video=document.querySelector('#camera');state.video.srcObject=state.stream;await state.video.play()}
function stopCamera(){if(state.stream){state.stream.getTracks().forEach(t=>t.stop());state.stream=null}}
function countdown(){return new Promise(res=>{const e=document.querySelector('#countdown');e.classList.remove('hidden');let n=3;e.textContent=n;const t=setInterval(()=>{n--;if(n<=0){clearInterval(t);e.classList.add('hidden');res()}else e.textContent=n},600)})}
function addScore(n){state.score+=n||1;document.querySelector('#gameScore').textContent=state.score;if(state.score>state.best){state.best=state.score;localStorage.setItem('camrush-best',state.best);document.querySelector('#bestScore').textContent=state.best}}
function finish(){cancelAnimationFrame(state.raf);stopCamera();document.querySelector('#gameStatus').textContent='ROUND OVER • '+state.score+' POINTS';document.querySelector('#gameTip').textContent='Hit RESTART to play again.'}
async function openGame(id){state.game=id;state.score=0;document.querySelector('#gameModal').classList.remove('hidden');const m=games.find(x=>x.id===id);document.querySelector('#gameTitle').textContent=m.title;document.querySelector('#gameTag').textContent=m.tag;document.querySelector('#gameScore').textContent='0';document.querySelector('#gameStatus').textContent='LOADING';document.querySelector('#gameTip').textContent=(id==='catch'||id==='pong')?'Show one hand • move naturally':'Keep your face in frame • move naturally';const l=document.querySelector('#loading');l.classList.remove('hidden');try{await startCamera();await loadVision();await countdown();startEngine(id)}catch(e){console.error(e);l.innerHTML='<b>Camera access is needed</b><small>Allow camera permission and try again.</small>';toast('Camera permission was not available.')}}
document.querySelector('#closeGame').onclick=()=>{cancelAnimationFrame(state.raf);stopCamera();document.querySelector('#gameModal').classList.add('hidden')};
document.querySelector('#restartGame').onclick=()=>state.game&&openGame(state.game);
document.querySelector('#playBtn').onclick=()=>openGame('catch');
grid.onclick=e=>{const c=e.target.closest('[data-game]');if(c)openGame(c.dataset.game)};

function canvas(){const c=document.querySelector('#gameCanvas'),r=c.parentElement.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);c.width=r.width*d;c.height=r.height*d;c.style.width=r.width+'px';c.style.height=r.height+'px';const x=c.getContext('2d');x.setTransform(d,0,0,d,0,0);return{x,w:r.width,h:r.height}}
function drawVideo(x,w,h){const v=state.video;if(!v||v.readyState<2)return;x.save();x.scale(-1,1);x.drawImage(v,-w,0,w,h);x.restore();x.fillStyle='rgba(4,7,15,.28)';x.fillRect(0,0,w,h)}
async function tracker(type){const {FilesetResolver,HandLandmarker,FaceLandmarker}=state.cv;const fs=await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22/wasm');const path=type==='hand'?'https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task':'https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task';const o={baseOptions:{modelAssetPath:path},runningMode:'VIDEO',minFaceDetectionConfidence:.5,minTrackingConfidence:.5};return type==='hand'?HandLandmarker.createFromOptions(fs,{...o,numHands:1,minHandDetectionConfidence:.5}):FaceLandmarker.createFromOptions(fs,{...o,numFaces:1,outputFaceBlendshapes:type==='smile'})}

async function gameCatch(){const {x,w,h}=canvas(),tr=await tracker('hand');let ts=[],last=0,end=performance.now()+45000;document.querySelector('#gameStatus').textContent='CATCH THE GLOW';function loop(now){if(now>end){finish();return}const r=tr.detectForVideo(state.video,now);drawVideo(x,w,h);if(now-last>650){last=now;ts.push({x:Math.random()*.8+.1,y:Math.random()*.65+.18,r:22+Math.random()*13,b:now})}const p=r.landmarks?.[0]?.[8];let px=-1e3,py=-1e3;if(p){px=(1-p.x)*w;py=p.y*h;x.beginPath();x.arc(px,py,9,0,7);x.strokeStyle='#fff';x.lineWidth=3;x.stroke()}ts=ts.filter(t=>now-t.b<1200);for(const t of ts){x.beginPath();x.arc(t.x*w,t.y*h,t.r,0,7);x.fillStyle='rgba(103,232,249,.15)';x.fill();x.strokeStyle='#67e8f9';x.lineWidth=3;x.stroke();if(Math.hypot(px-t.x*w,py-t.y*h)<t.r+15){addScore();t.b=0;t.r=0}}x.fillStyle='#fff';x.font='700 14px system-ui';x.fillText('TIME '+Math.ceil((end-now)/1000)+'s',18,28);state.raf=requestAnimationFrame(loop)}loop(performance.now())}
async function gameDodge(){const {x,w,h}=canvas(),tr=await tracker('face');let px=w/2,obs=[],last=0,start=performance.now(),survive=0;document.querySelector('#gameStatus').textContent='DODGE THE GATES';function loop(now){const r=tr.detectForVideo(state.video,now);drawVideo(x,w,h);const f=r.faceLandmarks?.[0]?.[1];if(f)px+=(1-f.x)*w-px;px=Math.max(35,Math.min(w-35,px));if(now-last>850){last=now;const gap=115+Math.random()*55;obs.push({y:-35,gx:45+Math.random()*(w-gap-90),gap})}for(const o of obs)o.y+=3.2+Math.min(4,(now-start)/12000);obs=obs.filter(o=>o.y<h+60);for(const o of obs){x.fillStyle='#a78bfa';x.fillRect(0,o.y,o.gx,25);x.fillRect(o.gx+o.gap,o.y,w-o.gx-o.gap,25);if(o.y>h*.72&&o.y<h*.72+25&&(px<o.gx+22||px>o.gx+o.gap-22)){finish();return}}if(Math.floor((now-start)/1000)>survive){survive++;addScore()}x.beginPath();x.arc(px,h*.78,18,0,7);x.fillStyle='#fff';x.fill();x.strokeStyle='#a78bfa';x.lineWidth=5;x.stroke();x.fillStyle='#fff';x.font='700 14px system-ui';x.fillText('SURVIVE '+survive+'s',18,28);state.raf=requestAnimationFrame(loop)}loop(performance.now())}
async function gameSmile(){const {x,w,h}=canvas(),tr=await tracker('smile');let charge=0,ts=[],last=0,end=performance.now()+45000;document.querySelector('#gameStatus').textContent='SMILE TO CHARGE';function smiling(r){const c=r.faceBlendshapes?.[0]?.categories||[];const a=c.find(q=>q.categoryName==='mouthSmileLeft')?.score||0,b=c.find(q=>q.categoryName==='mouthSmileRight')?.score||0;return(a+b)/2>.42}function loop(now){if(now>end){finish();return}const r=tr.detectForVideo(state.video,now);drawVideo(x,w,h);const s=smiling(r);charge=Math.max(0,Math.min(100,charge+(s?2.4:-.8)));if(now-last>650){last=now;ts.push({x:Math.random()*.8+.1,y:Math.random()*.65+.18,r:18+Math.random()*10})}if(charge>=100){addScore(3);charge=0;ts=[]}for(const t of ts){x.beginPath();x.arc(t.x*w,t.y*h,t.r,0,7);x.strokeStyle='#fb7185';x.lineWidth=3;x.stroke()}x.fillStyle='rgba(255,255,255,.14)';x.roundRect(18,h-38,w-36,14,7);x.fill();x.fillStyle='#fb7185';x.roundRect(18,h-38,(w-36)*charge/100,14,7);x.fill();x.fillStyle='#fff';x.font='700 13px system-ui';x.fillText(s?'SMILE!':'SMILE TO CHARGE',18,28);state.raf=requestAnimationFrame(loop)}loop(performance.now())}
async function gamePong(){const {x,w,h}=canvas(),tr=await tracker('hand');let paddle=w/2,bx=w/2,by=h*.45,vx=4,vy=4;document.querySelector('#gameStatus').textContent='KEEP IT ALIVE';function loop(now){const r=tr.detectForVideo(state.video,now);drawVideo(x,w,h);const p=r.landmarks?.[0]?.[8];if(p)paddle+=(1-p.x)*w-paddle;paddle=Math.max(75,Math.min(w-75,paddle));bx+=vx;by+=vy;if(bx<12||bx>w-12)vx*=-1;if(by<12)vy=Math.abs(vy);if(by>h-55&&by<h-25&&Math.abs(bx-paddle)<90){vy=-Math.abs(vy)*1.02;addScore()}if(by>h+30){finish();return}x.beginPath();x.arc(bx,by,11,0,7);x.fillStyle='#67e8f9';x.shadowBlur=20;x.shadowColor='#67e8f9';x.fill();x.shadowBlur=0;x.fillStyle='#fff';x.roundRect(paddle-72,h-34,144,14,7);x.fill();x.fillStyle='#fff';x.font='700 13px system-ui';x.fillText('MOVE YOUR HAND',18,28);state.raf=requestAnimationFrame(loop)}loop(performance.now())}
async function startEngine(id){document.querySelector('#loading').classList.add('hidden');if(id==='catch')return gameCatch();if(id==='dodge')return gameDodge();if(id==='smile')return gameSmile();return gamePong()}
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
